# Generated by Django 3.2.7 on 2024-03-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catering', '0002_cateringprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('food_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catering.fooditem')),
            ],
        ),
    ]
