# Generated by Django 5.0.1 on 2024-03-12 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods')),
                ('catering_name', models.CharField(max_length=200)),
                ('quantity_available', models.IntegerField(default=0)),
                ('quantity_booked', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
